name: Bug report
description: Report a problem so we can fix it
labels: [bug]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened and what did you expect?
      placeholder: Clear description of the bug
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: 1) Go to..., 2) Click..., 3) See error...
  - type: input
    id: url
    attributes:
      label: Page URL
      placeholder: https://...
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
  - type: dropdown
    id: browsers
    attributes:
      label: Browsers
      multiple: true
      options:
        - Chrome
        - Safari
        - Edge
        - Firefox
  - type: input
    id: device
    attributes:
      label: Device and OS
      placeholder: iPhone 14, iOS 17 / Windows 11 desktop, etc.