name: Feature request
description: Suggest an improvement or new feature
labels: [enhancement]
body:
  - type: textarea
    id: goal
    attributes:
      label: User goal
      description: What problem are we solving for the user?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the change. Include layout, components, copy.
  - type: checkboxes
    id: pages
    attributes:
      label: Pages impacted
      options:
        - label: Home
        - label: About
        - label: Therapies
        - label: Booking
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Bullet points that must be true to consider this done.